### ISSUE TITLE
weak

### ISSUE THREAD

**Issue by nfleclerc** [teddybear02/cwru-eecs293#1]

**Comment by teddybear02** [comment]
wow, you're right... totally forgot to up push my code lol

**Comment by teddybear02** [comment]
alright it's pushed. now tell me if it's weak...
... but really, lemme know how it could be improved :)

**Comment by nfleclerc** [comment]
Ur code is almost as smelly as u r

**Comment by nfleclerc** [comment]
Jk ur code looks nice

**Comment by nfleclerc** [comment]
Wait don't you have to do it in scala tho

**Comment by teddybear02** [comment]
Yes I do. I have it sitting on the back-burner rn
... It's not due yet and it's not even graded - my other classes get the priority for now

**Comment by teddybear02** [comment]
Oh, and I'd like to get set-up with Linux before I start working in Scala. Left my flash drive at home tho ughhh

**Comment by nfleclerc** [comment]
Buy a new one? They're like 2 bucks

**Comment by teddybear02** [comment]
Wait screw that - transitioning to Linux is only a suggestion so that the eecs293 team can help _"diagnose and fix problems due to obscure Windows configuration or registry settings"_ ... I don't need no help - I'm outtie

**Comment by teddybear02** [comment]
I got the Scala plugin for IntelliJ, and it works beautifully so far lol
